version: "3.9"

services:
  consumer-dataplane-zf:
    container_name: consumer-dataplane-zf
    build:
      context: ../edc-dataplane
      args:
        JAR: build/libs/edc.jar
    ports:
      - "29192:9191" # default (8192:9191)
      - "29183:9192" # public (8183:9192)
      - "25008:8090" # debugging
    environment:
      EDC_VAULT: /app/vault.properties
      EDC_KEYSTORE: /app/cert.pfx
      EDC_KEYSTORE_PASSWORD: 123456
      CONFIGURATION_PROPERTIES_FILE: /app/configuration.properties
      LOGGING_PROPERTIES_FILE: /app/logging.properties
      OPENTELEMETRY_PROPERTIES_FILE: /app/opentelemetry.properties
    volumes:
      - ./../certs/cert.pfx:/app/cert.pfx
      - ./zf/vault.properties:/app/vault.properties
      - ./zf/consumer_dp_configuration.properties:/app/configuration.properties
      - ./zf/opentelemetry.properties:/app/opentelemetry.properties
      - ./zf/logging.properties:/app/logging.properties

  consumer-controlplane-zf:
    container_name: consumer-controlplane-zf
    image: "edc-controlplane-memory-with-extension:latest"
    ports:
      - "28182:8282" # ids
      - "28185:8185" # public
      - "9000:9191" # default
      - "28192:9192" # validation
      - "28195:9193" # data
      - "28199:9999" # control
      - "25007:8090" # debugging
    environment:
      EDC_VAULT: /app/vault.properties
      EDC_KEYSTORE: /app/cert.pfx
      EDC_KEYSTORE_PASSWORD: 123456
      CONFIGURATION_PROPERTIES_FILE: /app/configuration.properties

    volumes:
      - ./../certs/cert.pfx:/app/cert.pfx
      - ./zf/vault.properties:/app/vault.properties
      - ./zf/consumer_cp_configuration.properties:/app/configuration.properties

  provider-controlplane-bosch:
    container_name: provider-controlplane-bosch
    build:
      context: ../edc-controlplane-memory
      args:
        JAR: build/libs/edc.jar
    ports:
      - "38081:9191" # default/control (8181:9191)
      - "38084:9192" # validation (8184:9192)
      - "38087:9193" # data (8187:9193)
      - "35005:8090" # debugging
      - "38181:8282" # ids
    environment:
      EDC_VAULT: /app/vault.properties
      EDC_KEYSTORE: /app/cert.pfx
      EDC_KEYSTORE_PASSWORD: 123456
      CONFIGURATION_PROPERTIES_FILE: /app/configuration.properties
      LOGGING_PROPERTIES_FILE: /app/logging.properties
      OPENTELEMETRY_PROPERTIES_FILE: /app/opentelemetry.properties
    volumes:
      - ./../certs/cert.pfx:/app/cert.pfx
      - ./bosch/vault.properties:/app/vault.properties
      - ./bosch/provider_cp_configuration.properties:/app/configuration.properties
      - ./bosch/opentelemetry.properties:/app/opentelemetry.properties
      - ./bosch/logging.properties:/app/logging.properties

  provider-dataplane-bosch:
    container_name: provider-dataplane-bosch
    build:
      context: ../edc-dataplane
      args:
        JAR: build/libs/edc.jar
    ports:
      - "39082:9191" # default (8182:9191)
      - "39083:9192" # public (8283:9192)
      - "35006:8090" # debugging
    environment:
      EDC_VAULT: /app/vault.properties
      EDC_KEYSTORE: /app/cert.pfx
      EDC_KEYSTORE_PASSWORD: 123456
      CONFIGURATION_PROPERTIES_FILE: /app/configuration.properties
      LOGGING_PROPERTIES_FILE: /app/logging.properties
      OPENTELEMETRY_PROPERTIES_FILE: /app/opentelemetry.properties
    volumes:
      - ./../certs/cert.pfx:/app/cert.pfx
      - ./bosch/vault.properties:/app/vault.properties
      - ./bosch/provider_dp_configuration.properties:/app/configuration.properties
      - ./bosch/opentelemetry.properties:/app/opentelemetry.properties
      - ./bosch/logging.properties:/app/logging.properties

  provider-controlplane-bmw:
    container_name: provider-controlplane-bmw
    build:
      context: ../edc-controlplane-memory
      args:
        JAR: build/libs/edc.jar
    ports:
      - "8081:9191" # default/control (8181:9191)
      - "8084:9192" # validation (8184:9192)
      - "8087:9193" # data (8187:9193)
      - "5005:8090" # debugging
      - "8181:8282" # ids
    environment:
      EDC_VAULT: /app/vault.properties
      EDC_KEYSTORE: /app/cert.pfx
      EDC_KEYSTORE_PASSWORD: 123456
      CONFIGURATION_PROPERTIES_FILE: /app/configuration.properties
      LOGGING_PROPERTIES_FILE: /app/logging.properties
      OPENTELEMETRY_PROPERTIES_FILE: /app/opentelemetry.properties
    volumes:
      - ./../certs/cert.pfx:/app/cert.pfx
      - ./bmw/vault.properties:/app/vault.properties
      - ./bmw/provider_cp_configuration.properties:/app/configuration.properties
      - ./bmw/opentelemetry.properties:/app/opentelemetry.properties
      - ./bmw/logging.properties:/app/logging.properties

  provider-dataplane-bmw:
    container_name: provider-dataplane-bmw
    build:
      context: ../edc-dataplane
      args:
        JAR: build/libs/edc.jar
    ports:
      - "9082:9191" # default (8182:9191)
      - "9083:9192" # public (8283:9192)
      - "5006:8090" # debugging
    environment:
      EDC_VAULT: /app/vault.properties
      EDC_KEYSTORE: /app/cert.pfx
      EDC_KEYSTORE_PASSWORD: 123456
      CONFIGURATION_PROPERTIES_FILE: /app/configuration.properties
      LOGGING_PROPERTIES_FILE: /app/logging.properties
      OPENTELEMETRY_PROPERTIES_FILE: /app/opentelemetry.properties
    volumes:
      - ./../certs/cert.pfx:/app/cert.pfx
      - ./bmw/vault.properties:/app/vault.properties
      - ./bmw/provider_dp_configuration.properties:/app/configuration.properties
      - ./bmw/opentelemetry.properties:/app/opentelemetry.properties
      - ./bmw/logging.properties:/app/logging.properties

  provider-controlplane-daimler:
    container_name: provider-controlplane-daimler
    build:
      context: ../edc-controlplane-memory
      args:
        JAR: build/libs/edc.jar
    ports:
      - "18081:9191" # default/control (8181:9191)
      - "18084:9192" # validation (8184:9192)
      - "18087:9193" # data (8187:9193)
      - "15005:8090" # debugging
      - "18181:8282" # ids
    environment:
      EDC_VAULT: /app/vault.properties
      EDC_KEYSTORE: /app/cert.pfx
      EDC_KEYSTORE_PASSWORD: 123456
      CONFIGURATION_PROPERTIES_FILE: /app/configuration.properties
      LOGGING_PROPERTIES_FILE: /app/logging.properties
      OPENTELEMETRY_PROPERTIES_FILE: /app/opentelemetry.properties
    volumes:
      - ./../certs/cert.pfx:/app/cert.pfx
      - ./daimler/vault.properties:/app/vault.properties
      - ./daimler/provider_cp_configuration.properties:/app/configuration.properties
      - ./daimler/opentelemetry.properties:/app/opentelemetry.properties
      - ./daimler/logging.properties:/app/logging.properties

  provider-dataplane-daimler:
    container_name: provider-dataplane-daimler
    build:
      context: ../edc-dataplane
      args:
        JAR: build/libs/edc.jar
    ports:
      - "19082:9191" # default (8182:9191)
      - "19083:9192" # public (8283:9192)
      - "15006:8090" # debugging
    environment:
      EDC_VAULT: /app/vault.properties
      EDC_KEYSTORE: /app/cert.pfx
      EDC_KEYSTORE_PASSWORD: 123456
      CONFIGURATION_PROPERTIES_FILE: /app/configuration.properties
      LOGGING_PROPERTIES_FILE: /app/logging.properties
      OPENTELEMETRY_PROPERTIES_FILE: /app/opentelemetry.properties
    volumes:
      - ./../certs/cert.pfx:/app/cert.pfx
      - ./daimler/vault.properties:/app/vault.properties
      - ./daimler/provider_dp_configuration.properties:/app/configuration.properties
      - ./daimler/opentelemetry.properties:/app/opentelemetry.properties
      - ./daimler/logging.properties:/app/logging.properties

  self-description-hub:
    container_name: self-description-hub
    build:
      context: ../../../self-description-hub-integration
      args:
        JAR: target/self-description-hub-integration-0.0.1-SNAPSHOT.jar
    ports:
      - "8090:8090"

  twin-registry-bmw:
    image: "registry:latest"
#    image: "ghcr.io/catenax-ng/catenax-at-home/registry:0.0.1"
    container_name: twin-registry-bmw
    environment:
      SPRING_PROFILES_ACTIVE: local
      SPRING_DATASOURCE_URL: jdbc:h2:file:./semantics/persistence;CASE_INSENSITIVE_IDENTIFIERS=TRUE
      IDP_ISSUER_URI: ""
    ports:
      - "4244:4243"

  twin-registry-daimler:
    image: "registry:latest"
#    image: "ghcr.io/catenax-ng/catenax-at-home/registry:0.0.1"
    container_name: twin-registry-daimler
    depends_on:
      - twin-registry-bmw
    environment:
      SPRING_PROFILES_ACTIVE: local
      SPRING_DATASOURCE_URL: jdbc:h2:file:./semantics/persistence;CASE_INSENSITIVE_IDENTIFIERS=TRUE
      IDP_ISSUER_URI: ""
    ports:
      - "4245:4243"

  twin-registry-bosch:
    image: "registry:latest"
#    image: "ghcr.io/catenax-ng/catenax-at-home/registry:0.0.1"
    container_name: twin-registry-bosch
    depends_on:
      - twin-registry-daimler
    environment:
      SPRING_PROFILES_ACTIVE: local
      SPRING_DATASOURCE_URL: jdbc:h2:file:./semantics/persistence;CASE_INSENSITIVE_IDENTIFIERS=TRUE
      IDP_ISSUER_URI: ""
    ports:
      - "4246:4243"
