# Copyright (c) 2022 Robert Bosch Manufacturing Solutions GmbH
#
# See the AUTHORS file(s) distributed with this work for additional
# information regarding authorship.
#
# See the LICENSE file(s) distributed with this work for
# additional information regarding license terms.
#

server:
  port: 8080

spring:
  thymeleaf:
    cache: false

asset:
  retriever: mock

registry:
  edc-location:
    provider: rest

self:
  description:
    hub:
      url: localhost:8090/self-desc-hub/

consumer:
  control:
    plane: http://localhost:28195

springdoc:
  cache:
    disabled: true
  api-docs:
    enabled: false
  swagger-ui:
    path: /swagger-ui
    urls:
      - name: Explorer API
        url: /explorer-openapi.yaml